<<<<<<< HEAD
dependencyResolutionManagement {
    repositories.gradlePluginPortal()
}

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()

        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://repo.crazycrew.us/api/")
    }
}

rootProject.name = "CrazyUnions"

val lowerCase = rootProject.name.lowercase()

//listOf("api").forEach(::includeProject)

fun includeProject(name: String) {
    include(name) {
        this.name = "$lowerCase-$name"
    }
}

fun include(name: String, block: ProjectDescriptor.() -> Unit) {
    include(name)
    project(":$name").apply(block)
}
=======
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "FactionsX-Parent"
include(":AddonFramework")
include(":FactionsX")
include("FactionsUUIDAPIProxy")
include(":FTOP-Addon")
include(":FWild-Addon")
include(":FGrace-Addon")
include(":FTNT-Addon")
include(":FPrinter-Addon")
include(":FMobTweaks-Addon")
include(":FRoam-Addon")
include(":FChest-Addon")
include(":FRoster-Addon")
include(":FDynmap-Addon")
include(":FShop-Addon")
include(":FCropUpgrades-Addon")
include(":FMaxTileEntities-Addon")
include(":FactionsUUIDAPIProxy")
include(":FEssentials-Addon")
>>>>>>> master
